version: '3'
services:
  php-apache:
    build:
      context: ../php_7
      dockerfile: Dockerfile
    container_name: 'php-7.1'
    ports:
      - 80:80
    volumes:
      - ../../php/:/var/www/html
