version: '3'
services:
  php-apache:
    build:
      context: ../php_7
      dockerfile: Dockerfile
    container_name: 'php-7.1'
    ports:
      - 80:80
    volumes:
      - ../../php/:/var/www/html
    networks:
      - sampletest
      - default
  db:
    build:
      context: ../mysql
      dockerfile: Dockerfile
    container_name: 'db'
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ../mysql/init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ../mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - sampletest
      - default
networks:
  sampletest:
    external: true
