version: '3'
services:
  php-apache:
    build:
      context: ../php_5
      dockerfile: Dockerfile
    container_name: 'php-5.6'
    ports:
      - 8080:80
    volumes:
      - ../../php/:/var/www/html
    networks:
      - sampletest
      - default
networks:
  sampletest:
    external: true
